# Generated by Django 2.0.2 on 2019-12-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='update',
            new_name='updated',
        ),
    ]
